# Generated by Django 4.2 on 2025-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_water_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Холодна вода 1')),
                ('cold_water_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Холодна вода 2')),
                ('hot_water_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Гаряча вода 1')),
                ('hot_water_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Гаряча вода 2')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подання')),
            ],
        ),
    ]
