# Generated by Django 4.2 on 2025-01-09 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
