# Generated by Django 4.2 on 2025-01-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'verbose_name': 'Лічильник', 'verbose_name_plural': 'Лічильники'},
        ),
    ]
